Make sure cd doesn’t fail
One of the side benefits of blogging about code is that you get it
reviewed by lots of clever internet people. A couple of them
pointed out another bug in the _mysociety_commonlib_directory
function: it would return the wrong answer if the cd command failed
for some reason (bad permissions on the commonlib directory being
the obvious possible cause).

Thanks to:
 - DoesntSmellRight on http://www.reddit.com/r/programming/comments/pmgxa/a_littleknown_trap_for_the_unwary_bash_scripter/c3qp8ds
 - geirha on http://bosker.wordpress.com/2012/02/12/bash-scripters-beware-of-the-cdpath/#comment-2516

diff --git a/shlib/deployfns b/shlib/deployfns
--- a/shlib/deployfns
+++ b/shlib/deployfns
@@ -21,15 +21,18 @@ _mysociety_commonlib_directory() {
     (
       unset CDPATH  # Restore cd to its default behaviour, in case the
                     # environment has a CDPATH defined.
-                    #
-                    # Also ignore the stdout output of cd, just in case
-                    # there is some other reason than having a CDPATH that
-                    # cd might produce output.
-      cd "$(dirname "${BASH_SOURCE[0]}")"/.. > /dev/null
-      pwd
+                    # Do this in the subshell, to avoid messing with the
+                    # caller’s environment.
+      cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd
     )
 }
 MYSOCIETY_COMMONLIB_DIR=$(_mysociety_commonlib_directory)
+if [ $? -ne 0 ]
+then
+    # If cd or pwd failed for some reason, they will have already
+    # printed an error message to stderr.
+    exit $?
+fi
 
 # Reads in config file
 # If $1 ends with .yml, it is loaded as YAML. Otherwise
